### ISSUE TITLE
Mixed implementation of pipe and compose

### ISSUE THREAD

**Issue by snak1t** [codedojo/javascript-fp#1]
Привет, в файле `javascript-fp/04_composition/composition.js` у тебе немного перепутаны реализации функций pipe и compose

У тебя идет:
```
function compose(...funcs) {
    return funcs.reduce((fn1, fn2) => (...args) => fn2(fn1(...args)));
}

function pipe(...funcs) {
    return funcs.reduceRight((fn1, fn2) => (...args) => fn1(fn2(...args)));
}
```
А должно быть
```
function compose(...funcs) {
  return funcs.reduceRight((fn1, fn2) => (...args) => fn2(fn1(...args)));
}

function pipe(...funcs) {
  return funcs.reduce((fn1, fn2) => (...args) => fn2(fn1(...args)));
}
```
В твоей реализации и pipe и compose ведут себя совершенно одинаково. Источник правды https://github.com/getify/Functional-Light-JS/blob/master/ch4.md подзаголовок Alternate implementations

**Comment by olegpolyakov** [comment]
Привет! Спасибо за замечание. С этими вызовами очень легко запутаться. Внес поправки в исходный код, сейчас функции правильно работают. Я правда в `compose` оставил `reduce`, а в `pipe` - `reduceRight`, просто поменял порядок выполнения.

**Comment by snak1t** [comment]
Да от перестановки reduce и reduceRight главное чтобы порядок не менялся. Вон у того же Кайла Симпсона, да и у многих других, функция compose реализованна через fns.reverse().reduce(...).
